import './globals.css'

import type { Metadata } from 'next'
import { Jua as FontAlt, Source_Sans_3 as FontSans } from 'next/font/google'

import Background from '@/components/shared/background'
import Logo from '@/components/shared/logo'
import { Toaster } from '@/components/ui/sonner'
import { cn } from '@/lib/utils'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

const fontAlt = FontAlt({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-alt',
})

export const metadata: Metadata = {
  title: 'Todo List - StartTec',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'relative min-h-screen overflow-x-hidden bg-background font-sans antialiased',
          fontSans.variable,
          fontAlt.variable,
        )}
      >
        <header className="flex flex-col items-center pt-10 md:pt-[72px]">
          <Logo />
        </header>
        {children}
        <Toaster />
        <Background />
      </body>
    </html>
  )
}
